### ISSUE TITLE
Alternative implementation

### ISSUE THREAD

**Issue by vmaffione** [selvakumar8292/mystorm#1]
Hi!
  Sorry for writing this message here, but I've seen that you are interested in trying RINA over TCP/UDP, and tried to use our project IRATI (https://github.com/IRATI/stack/issues/1060).
In case you are still interested, we also have an alternative newer RINA implementation available (called rlite), that is intended to be easier in terms of configuration, and it is available here https://github.com/vmaffione/rlite .

Some important differences with IRATI:
 - no kernel recompilation is necessary, since the stack is implemented as independent kernel modules; this means that it will take 60 seconds or less to compile.
- configuration is similar to TCP/IP (ifconfig/iproute2-like command-line tools), so no configuration files.
- documentation is self-contained in README.md file (just scroll down the main repo page).

There is a quick and straight-to-the-point tutorial on how to setup RINA over UDP, that is section 4.3 in the README.md .

If you happen to try it, we will be happy to hear your feedback, of any type!

Thanks a lot for your attention!

**Comment by selvakumar8292** [comment]
thanks for your feedback. I saw that project too. Good job I will try when I get chance.

**Comment by vmaffione** [comment]
Thanks!
If you are interested, we (the RINA research team) have also published the project in the official PSOC website
http://www.pouzinsociety.org/implementations/rlite

Cheers,
  Vincenzo
